from typing import TypedDict, List, NamedTuple
from BaseClasses import ItemClassification, Item
from worlds.pokemon_colo.Helpers import PCItemType
from .Strings import Items, Events
from .Options import ColosseumOptions, ColosseumSanity

base_id = 159700

class PCItemData(NamedTuple):
    item_id: int = -1
    """
    Internal item ID. If a Pokemon, is the Pokemon's internal ID
    """
    item_type: PCItemType = PCItemType.NONE
    amount: int = -1
    shadow_id: int = -1
    """
    Used only for the Pokemon PCItemType. Denotes what the shadow ID should be.
    """
    level: int = -1
    """
    Used only for the Pokemon PCItemType. Sets what the default level should be of the shadow Pokemon
    """
    move_id: List[int] = [None, None, None, None]
    """
    Used only for the Pokemon PCItemType. The Move IDs of the default moves of the specified Pokemon
    """
    move_pp: List[int] = [None, None, None, None]
    """
    Used only for the Pokemon PCItemType. The PP of the given moves above.
    """

class ColosseumItem(Item):
    game: str = "Pokemon Colosseum"

class ItemDesc(TypedDict):
    name: str
    count: int
    classification: ItemClassification
    data: PCItemData

shadow_pokemon: List[ItemDesc] = [
    {'name': Items.Progression.makuhita,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=335, item_type=PCItemType.POKEMON, amount=1, shadow_id=1, level=30, move_id=[193, 116, 233, 238], move_pp=[40, 30, 10, 5])},
    {'name': Items.Progression.bayleef,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=152, item_type=PCItemType.POKEMON, amount=1, shadow_id=2, level=30, move_id=[241, 235, 75, 34], move_pp=[])},
    {'name': Items.Progression.quilava,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=156, item_type=PCItemType.POKEMON, amount=1, shadow_id=3, level=30, move_id=[241, 108, 91, 172], move_pp=[])},
    {'name': Items.Progression.croconaw,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=159, item_type=PCItemType.POKEMON, amount=1, shadow_id=4, level=30, move_id=[240, 184, 44, 57], move_pp=[])},
    {'name': Items.Progression.slugma,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=218, item_type=PCItemType.POKEMON, amount=1, shadow_id=5, level=30, move_id=[241, 281, 88, 53], move_pp=[])},
    {'name': Items.Progression.misdreavus,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=200, item_type=PCItemType.POKEMON, amount=1, shadow_id=6, level=30, move_id=[60, 109, 212, 247], move_pp=[])},
    {'name': Items.Progression.noctowl,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=164, item_type=PCItemType.POKEMON, amount=1, shadow_id=7, level=30, move_id=[211, 95, 115, 19], move_pp=[])},
    {'name': Items.Progression.flaffy,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=180, item_type=PCItemType.POKEMON, amount=1, shadow_id=8, level=30, move_id=[85, 86, 178, 84], move_pp=[])},
    {'name': Items.Progression.skiploom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=188, item_type=PCItemType.POKEMON, amount=1, shadow_id=9, level=30, move_id=[235, 79, 178, 72], move_pp=[])},
    {'name': Items.Progression.quagsire,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=195, item_type=PCItemType.POKEMON, amount=1, shadow_id=10, level=30, move_id=[341, 133, 21, 57], move_pp=[])},
    {'name': Items.Progression.furret,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=162, item_type=PCItemType.POKEMON, amount=1, shadow_id=11, level=33, move_id=[231, 270, 98, 70], move_pp=[])},
    {'name': Items.Progression.yanma,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=193, item_type=PCItemType.POKEMON, amount=1, shadow_id=12, level=33, move_id=[197, 48, 49, 253], move_pp=[])},
    {'name': Items.Progression.remoraid,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=223, item_type=PCItemType.POKEMON, amount=1, shadow_id=13, level=20, move_id=[61, 199, 60, 62], move_pp=[])},
    {'name': Items.Progression.mantine,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=226, item_type=PCItemType.POKEMON, amount=1, shadow_id=14, level=33, move_id=[17, 48, 61, 36], move_pp=[])},
    {'name': Items.Progression.qwilfish,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=211, item_type=PCItemType.POKEMON, amount=1, shadow_id=15, level=33, move_id=[42, 107, 40, 57], move_pp=[])},
    {'name': Items.Progression.meditite,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=336, item_type=PCItemType.POKEMON, amount=1, shadow_id=16, level=33, move_id=[197, 347, 93, 136], move_pp=[])},
    {'name': Items.Progression.dunsparce,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=206, item_type=PCItemType.POKEMON, amount=1, shadow_id=17, level=33, move_id=[180, 137, 281, 36], move_pp=[])},
    {'name': Items.Progression.swablu,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=338, item_type=PCItemType.POKEMON, amount=1, shadow_id=18, level=33, move_id=[119, 47, 219, 19], move_pp=[])},
    {'name': Items.Progression.sudowoodo,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=185, item_type=PCItemType.POKEMON, amount=1, shadow_id=19, level=35, move_id=[175, 335, 67, 157], move_pp=[])},
    {'name': Items.Progression.hitmontop,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=237, item_type=PCItemType.POKEMON, amount=1, shadow_id=20, level=38, move_id=[97, 116, 167, 229], move_pp=[])},
    {'name': Items.Progression.entei,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=244, item_type=PCItemType.POKEMON, amount=1, shadow_id=21, level=40, move_id=[241, 43, 44, 126], move_pp=[])},
    {'name': Items.Progression.ledian,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=166, item_type=PCItemType.POKEMON, amount=1, shadow_id=22, level=40, move_id=[226, 219, 48, 36], move_pp=[])},
    {'name': Items.Progression.suicune,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=245, item_type=PCItemType.POKEMON, amount=1, shadow_id=23, level=40, move_id=[240, 43, 16, 56], move_pp=[])},
    {'name': Items.Progression.gligar,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=207, item_type=PCItemType.POKEMON, amount=1, shadow_id=24, level=43, move_id=[185, 28, 40, 163], move_pp=[])},
    {'name': Items.Progression.stantler,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=234, item_type=PCItemType.POKEMON, amount=1, shadow_id=25, level=43, move_id=[310, 95, 43, 36], move_pp=[])},
    {'name': Items.Progression.piloswine,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=221, item_type=PCItemType.POKEMON, amount=1, shadow_id=26, level=43, move_id=[203, 316, 91, 59], move_pp=[])},
    {'name': Items.Progression.sneasel,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=215, item_type=PCItemType.POKEMON, amount=1, shadow_id=27, level=43, move_id=[185, 103, 154, 196], move_pp=[])},
    {'name': Items.Progression.aipom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=190, item_type=PCItemType.POKEMON, amount=1, shadow_id=28, level=43, move_id=[226, 321, 154, 129], move_pp=[])},
    {'name': Items.Progression.murkrow,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=198, item_type=PCItemType.POKEMON, amount=1, shadow_id=29, level=43, move_id=[185, 212, 101, 19], move_pp=[])},
    {'name': Items.Progression.forretress,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=205, item_type=PCItemType.POKEMON, amount=1, shadow_id=30, level=43, move_id=[153, 182, 117, 229], move_pp=[])},
    {'name': Items.Progression.ariados,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=168, item_type=PCItemType.POKEMON, amount=1, shadow_id=31, level=43, move_id=[169, 184, 141, 188], move_pp=[])},
    {'name': Items.Progression.granbull,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=210, item_type=PCItemType.POKEMON, amount=1, shadow_id=32, level=43, move_id=[44, 184, 46, 70], move_pp=[])},
    {'name': Items.Progression.vibrava,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=333, item_type=PCItemType.POKEMON, amount=1, shadow_id=33, level=43, move_id=[242, 103, 328, 225], move_pp=[])},
    {'name': Items.Progression.raikou,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=243, item_type=PCItemType.POKEMON, amount=1, shadow_id=34, level=40, move_id=[240, 43, 98, 87], move_pp=[])},
    {'name': Items.Progression.sunflora,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=192, item_type=PCItemType.POKEMON, amount=1, shadow_id=35, level=45, move_id=[241, 74, 275, 76], move_pp=[])},
    {'name': Items.Progression.delibird,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=225, item_type=PCItemType.POKEMON, amount=1, shadow_id=36, level=45, move_id=[59, 213, 217, 19], move_pp=[])},
    {'name': Items.Progression.heracross,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=214, item_type=PCItemType.POKEMON, amount=1, shadow_id=37, level=45, move_id=[], move_pp=[])},
    {'name': Items.Progression.skarmory,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=227, item_type=PCItemType.POKEMON, amount=1, shadow_id=38, level=47, move_id=[], move_pp=[])},
    {'name': Items.Progression.miltank,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=241, item_type=PCItemType.POKEMON, amount=1, shadow_id=39, level=48, move_id=[], move_pp=[])},
    {'name': Items.Progression.absol,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=376, item_type=PCItemType.POKEMON, amount=1, shadow_id=40, level=48, move_id=[], move_pp=[])},
    {'name': Items.Progression.houndoom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=229, item_type=PCItemType.POKEMON, amount=1, shadow_id=41, level=48, move_id=[], move_pp=[])},
    {'name': Items.Progression.tropius,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=369, item_type=PCItemType.POKEMON, amount=1, shadow_id=42, level=49, move_id=[], move_pp=[])},
    {'name': Items.Progression.metagross,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=400, item_type=PCItemType.POKEMON, amount=1, shadow_id=43, level=50, move_id=[], move_pp=[])},
    {'name': Items.Progression.tyranitar,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=248, item_type=PCItemType.POKEMON, amount=1, shadow_id=44, level=55, move_id=[], move_pp=[])}
]

post_game_shadows: List[ItemDesc] = [
    {'name': Items.Progression.smeargle,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=235, item_type=PCItemType.POKEMON, amount=1, shadow_id=45, level=45, move_id=[], move_pp=[])},
    {'name': Items.Progression.ursaring,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=217, item_type=PCItemType.POKEMON, amount=1, shadow_id=46, level=45, move_id=[], move_pp=[])},
    {'name': Items.Progression.shuckle,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=213, item_type=PCItemType.POKEMON, amount=1, shadow_id=47, level=45, move_id=[], move_pp=[])},
    {'name': Items.Progression.togetic,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=176, item_type=PCItemType.POKEMON, amount=1, shadow_id=48, level=20, move_id=[], move_pp=[])}
]

prog_items: List[ItemDesc] = [
    {'name': Items.Progression.region_unlock,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.colosseum_unlock,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.rui,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.gear,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=532, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.red_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=533, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.green_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=534, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.blue_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=535, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.yellow_id,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=536, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.small_tablet,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=502, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.f_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=503, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.time_flute, # Only 1 is progression, do not know how to get the other two as useful
     'count': 3,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=537, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Progression.jail_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=500, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.elevator_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=501, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.powerup_part,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=546, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.r_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=504, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.subway_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=508, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.u_disk,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=507, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.maingate_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=509, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.card_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=510, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.down_st_key,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=511, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.data_rom,
     'count': 1,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=530, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Progression.dna_sample, # There are 18 DNA Samples ID 512-529
     'count': 3,
     'classification': ItemClassification.progression,
     'data': PCItemData(item_id=512, item_type=PCItemType.KEYITEM, amount=1)}
]

colosseum_round_items: List[ItemDesc] = [
    {'name': Items.Progression.phenac_round_pass,
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.pyrite_round_pass,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.under_round_pass,
     'count': 3,
     'classification': ItemClassification.progression,
     'data': None},
    {'name': Items.Progression.deep_round_pass,
     'count': 4,
     'classification': ItemClassification.progression,
     'data': None}
]

useful_items: List[ItemDesc] = [ 
    {'name': Items.Useful.cologne_case,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=542, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.l_disk,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=505, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.d_disk,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=506, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.steel_teeth,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=531, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.ein_file_h,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=539, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.ein_file_s,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=538, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.ein_file_p,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=541, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.ein_file_c,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=540, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.ein_file_f,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=547, item_type=PCItemType.KEYITEM, amount=1)},
    {'name': Items.Useful.masterball,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=1, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Useful.maxpotion,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=20, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Useful.fullrestore,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=19, item_type=PCItemType.ITEM, amount=3)},
     {'name': Items.Useful.fullheal,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=23, item_type=PCItemType.ITEM, amount=3)},
     {'name': Items.Useful.maxrevive,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=25, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Useful.rare_candy,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=68, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Useful.pp_max,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=71, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Useful.star_piece,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=109, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Useful.nugget,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=110, item_type=PCItemType.ITEM, amount=2)},
    {'name': Items.Useful.exp_share,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=182, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.quick_claw,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=183, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.silk_scarf,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=217, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.leftovers,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=200, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.scope_lens,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=198, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.lucky_egg,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=197, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.macho_brace,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=181, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.white_herb,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=180, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.choice_band,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=186, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.focus_band,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=196, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Useful.tm_01,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=289, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_02,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=290, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_03,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=291, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_04,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=292, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_05,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=293, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_06,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=294, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_07,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=295, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_08,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=296, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_09,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=297, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_10,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=298, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_11,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=299, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_12,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=300, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_13,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=301, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_14,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=302, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_15,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=303, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_16,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=304, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_17,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=305, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_18,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=306, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_19,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=307, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_20,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=308, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_21,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=309, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_22,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=310, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_23,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=311, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_24,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=312, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_25,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=313, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_26,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=314, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_27,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=315, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_28,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=316, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_29,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=317, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_30,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=318, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_31,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=319, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_32,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=320, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_33,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=321, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_34,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=322, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_35,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=323, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_36,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=324, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_37,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=325, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_38,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=326, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_39,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=327, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_40,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=328, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_41,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=329, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_42,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=330, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_43,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=331, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_44,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=332, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_45,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=333, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_46,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=334, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_47,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=335, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_48,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=336, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_49,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=337, item_type=PCItemType.TM, amount=1)},
    {'name': Items.Useful.tm_50,
     'count': 1,
     'classification': ItemClassification.useful,
     'data': PCItemData(item_id=338, item_type=PCItemType.TM, amount=1)},
]

filler: List[ItemDesc] = [
    {'name': Items.Filler.pokeball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=4, item_type=PCItemType.POKEBALL, amount=5)},
    {'name': Items.Filler.greatball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=3, item_type=PCItemType.POKEBALL, amount=3)},
    {'name': Items.Filler.ultraball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=2, item_type=PCItemType.POKEBALL, amount=2)},
     {'name': Items.Filler.netball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=6, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Filler.diveball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=7, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Filler.nestball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=8, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Filler.repeatball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=9, item_type=PCItemType.POKEBALL, amount=1)},
    {'name': Items.Filler.timerball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=10, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Filler.luxuryball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=11, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Filler.premierball,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=12, item_type=PCItemType.POKEBALL, amount=1)},
     {'name': Items.Filler.potion,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=13, item_type=PCItemType.ITEM, amount=3)},
     {'name': Items.Filler.superpotion,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=22, item_type=PCItemType.ITEM, amount=2)},
     {'name': Items.Filler.hyperpotion,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=21, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.antidote,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=14, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.burnheal,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=15, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.iceheal,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=16, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.awakening,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=17, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.parlyzheal,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=18, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.revive,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=24, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.freshwater,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=26, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.sodapop,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=27, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.lemonade,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=28, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.moomoo_milk,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=29, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.energy_powder,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=30, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.energy_root,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=31, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.heal_powder,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=32, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.revival_herb,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=33, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.ether,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=34, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.maxether,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=35, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.elixir,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=36, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.maxelixir,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=37, item_type=PCItemType.ITEM, amount=1)},
     {'name': Items.Filler.hp_up,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=63, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.protein,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=64, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.iron,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=65, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.carbos,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=66, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.calcium,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=67, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.pp_up,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=69, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.zinc,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=70, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.guard_spec,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=73, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.dire_hit,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=74, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.x_attack,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=75, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.x_defend,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=76, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.x_speed,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=77, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.x_accuracy,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=78, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.x_special,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=79, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.sun_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=93, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.moon_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=94, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.fire_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=95, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.thunder_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=96, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.water_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=97, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.leaf_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=98, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.pearl,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=106, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.big_pearl,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=107, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.stardust,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=108, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.cheri_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=133, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.chesto_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=134, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.pecha_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=135, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.rawst_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=136, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.aspear_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=137, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.leppa_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=138, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.oran_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=139, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.persim_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=140, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.lum_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=141, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.sitrus_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=142, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.figy_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=143, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.wiki_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=144, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.mago_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=145, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.aguav_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=146, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.iapapa_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=147, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.razz_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=148, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.bluk_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=149, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.nanab_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=150, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.wepear_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=151, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.pinap_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=152, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.pomeg_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=153, item_type=PCItemType.BERRY, amount=1)},     
    {'name': Items.Filler.kelpsy_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=154, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.qualot_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=155, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.hondew_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=156, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.grepa_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=157, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.tamato_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=158, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.cornn_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=159, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.magost_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=160, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.rabuta_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=161, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.nomel_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=162, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.spelon_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=163, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.pamtre_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=164, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.watmel_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=165, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.durin_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=166, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.belune_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=167, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.liechi_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=168, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.ganlon_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=169, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.salac_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=170, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.petaya_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=171, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.apicot_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=172, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.lansat_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=173, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.starf_berry,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=174, item_type=PCItemType.BERRY, amount=1)},
    {'name': Items.Filler.bright_powder,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=179, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.silver_powder,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=188, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.amulet_coin,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=189, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.soft_sand,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=203, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.hard_stone,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=204, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.miracle_seed,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=205, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.black_glasses,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=206, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.black_belt,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=207, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.magnet,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=208, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.mystic_water,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=209, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.sharp_beak,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=210, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.poison_barb,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=211, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.never_melt_ice,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=212, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.spell_tag,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=213, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.twisted_spoon,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=214, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.charcoal,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=215, item_type=PCItemType.ITEM, amount=1)},
    {'name': Items.Filler.dragon_fang,
     'count': 1,
     'classification': ItemClassification.filler,
     'data': PCItemData(item_id=216, item_type=PCItemType.ITEM, amount=1)},
]

event_items: List[ItemDesc] = [
    {'name': Events.goal,
     'count': 0, # In case it somehow get into used_items it will not be added
     'classification': ItemClassification.progression},     
    {'name': Items.Progression.dakim_defeated,
     'count': 0, # In case it somehow get into used_items it will not be added
     'classification': ItemClassification.progression},     
    {'name': Items.Progression.mirorb_defeated,
     'count': 0, # In case it somehow get into used_items it will not be added
     'classification': ItemClassification.progression},     
    {'name': Items.Progression.dukings_mail_read,
     'count': 0, # In case it somehow get into used_items it will not be added
     'classification': ItemClassification.progression}
]

all_items = prog_items + shadow_pokemon + useful_items + filler + colosseum_round_items + post_game_shadows + event_items

def set_items_used(options: ColosseumOptions) -> List[ItemDesc]:
    # Set items to be used in the multiworld here to used_items
    used_items = []
    used_items.extend(prog_items)
    used_items.extend(shadow_pokemon)

    if options.postgame_shadow_pokemon:
        used_items.extend(post_game_shadows)

    used_items.extend(useful_items)
    if options.colosseum_sanity != ColosseumSanity.option_off:
        used_items.extend(colosseum_round_items)
    return used_items