option_presets = {
    "Default Bayleef": {
        "goal": 0,
        "realgam_tower_unlock": 0,
        "purify_unlock_amount": 26,
        "rui_unlock": 1,
        "shadow_pokemon_as_items": True,
        "phenac_starter_choice": 0,
        "postgame_shadow_pokemon": False,
        "difficulty": 1,
        "add_mt_battle": False,
        "mirakle_b": False,
        "colosseum_sanity": 0,
    },
    "Default Quilava": {
        "goal": 0,
        "realgam_tower_unlock": 0,
        "purify_unlock_amount": 26,
        "rui_unlock": 1,
        "shadow_pokemon_as_items": True,
        "phenac_starter_choice": 1,
        "postgame_shadow_pokemon": False,
        "difficulty": 1,
        "add_mt_battle": False,
        "mirakle_b": False,
        "colosseum_sanity": 0,
    },
    "Default Croconaw": {
        "goal": 0,
        "realgam_tower_unlock": 0,
        "purify_unlock_amount": 26,
        "rui_unlock": 1,
        "shadow_pokemon_as_items": True,
        "phenac_starter_choice": 2,
        "postgame_shadow_pokemon": False,
        "difficulty": 1,
        "add_mt_battle": False,
        "mirakle_b": False,
        "colosseum_sanity": 0,
    }
}
