from typing import Dict, List
from .Strings import Regions

colo_regions_all: Dict[str, List[str]] = {
    Regions.menu: [Regions.phenac, Regions.outside_city, Regions.pyrite, Regions.construction, Regions.agate, Regions.mt_battle, Regions.lab, Regions.realgam, Regions.snagem],
    Regions.phenac: [Regions.phenac_city_pregym, Regions.phenac_colosseum],
    Regions.phenac_city_pregym: [],
    Regions.phenac_colosseum: [Regions.phenac_colosseum_r2],
    Regions.phenac_colosseum_r2: [Regions.phenac_colosseum_r3],
    Regions.phenac_colosseum_r3: [Regions.phenac_colosseum_r4],
    Regions.phenac_colosseum_r4: [],
    Regions.outside_city: [],
    Regions.pyrite: [Regions.pyrite_building, Regions.pyrite_colosseum, Regions.pyrite_2, Regions.pyrite_jail_cell],
    Regions.pyrite_building: [Regions.pyrite_cave, Regions.the_under],
    Regions.pyrite_cave: [],
    Regions.the_under: [Regions.the_under_2, Regions.the_under_f, Regions.the_under_r, Regions.the_under_u],
    Regions.the_under_2: [],
    Regions.the_under_r: [],
    Regions.the_under_f: [Regions.under_colosseum],
    Regions.the_under_u: [],
    Regions.under_colosseum: [Regions.under_colosseum_r2],
    Regions.under_colosseum_r2: [Regions.under_colosseum_r3],
    Regions.under_colosseum_r3: [Regions.under_colosseum_r4],
    Regions.under_colosseum_r4: [],
    Regions.pyrite_colosseum: [Regions.pyrite_colosseum_r1],
    Regions.pyrite_colosseum_r1: [Regions.pyrite_colosseum_r2],
    Regions.pyrite_colosseum_r2: [Regions.pyrite_colosseum_r3],
    Regions.pyrite_colosseum_r3: [Regions.pyrite_colosseum_r4],
    Regions.pyrite_colosseum_r4: [],
    Regions.pyrite_2: [],
    Regions.pyrite_jail_cell: [],
    Regions.construction: [],
    Regions.agate: [Regions.purify],
    Regions.purify: [],
    Regions.mt_battle: [],
    Regions.lab: [Regions.lab_main, Regions.lab_station, Regions.lab_shutter],
    Regions.lab_main: [Regions.lab_main_after_key],
    Regions.lab_main_after_key: [],
    Regions.lab_station: [],
    Regions.lab_shutter: [],
    Regions.realgam: [Regions.pre_final],
    Regions.pre_final: [Regions.final],
    Regions.final: [],
    Regions.snagem: []
}
